from . import mofi_branch
from . import mofi_channel
from . import leasing_contract
from . import mofi_funding_type
from . import mofi_loan_purpose
from . import mofi_order_type
from . import mofi_suborder_type
from . import mofi_fee_type
from . import mofi_payment_channel
from . import mofi_leasing_account
from . import res_partner
from . import mofi_leasing_amortization
from . import account_move
from . import mofi_leasing_contract
from . import mofi_bank_account_no
from . import account_journal